### ISSUE TITLE
Constant paths specification

### ISSUE THREAD

**Issue by so-phi** [matsengrp/gestaltamania#173]
Could you specify in a bit more detail, to which phylip executables the constant path file should point?

I can only see the path variable names in [the import statement in tree_distance.py](https://github.com/matsengrp/gestaltamania/blob/f7986fa07a5832bb7efcb328c54d6c9b06e31e69/gestalt/tree_distance.py#L12). But only from those it's difficult to figure out.

**Comment by so-phi** [comment]
For anyone interested - I had to download 2 more packages, rspr and BHVtreespace, and link their respective executables.  That's what my constant_paths.py file looks like:

```
# from https://github.com/cwhidden/rspr
RSPR_PATH=".../rspr-master/rspr"

# from https://github.com/gavruskin/tauGeodesic
#could be a different program within the BHV package.... in distances only robinson Foulds distance is used
BHV_PATH=".../BHVtreespace-master/Distances.jar"

# from within gestaltamania 
TAU_GEO_JAR_PATH=".../gestaltamania-master/tauSpace/tauGeodesic.jar"

# as specified on gestaltamania README
MIX_PATH=".../phylip-3.695/exe/mix"
```

**Comment by jjfeng** [comment]
Hi, thank you for your interest! Yes, this is exactly what the constant_paths.py file should look like. I will add a note in the repo.
